#!/usr/bin/env python3
"""Parse scraps/bwv1043_gbc.h and emit dictionary-packed src/bwv1043_music.c.

Each note is a 1-byte index into a ≤256-entry (freq, dur) table.
Total ~2.9 KB — fits flat 32 KiB ROM with no MBC banking."""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRAP = ROOT / "scraps" / "bwv1043_gbc.h"
SRC_C = ROOT / "src" / "bwv1043_music.c"
SRC_H = ROOT / "src" / "bwv1043_music.h"

PRELUDE_FRAC = 0.35
VBL_HZ = 59.7275
VBL_PER_16TH = (60.0 / 4.0 / 110.0) * VBL_HZ
SENTINEL_IDX = 0xFF


def midi_to_gb_freq_reg(midi: int) -> int:
    hz = 440.0 * (2.0 ** ((float(midi) - 69.0) / 12.0))
    return int(2048.0 - 131072.0 / hz) & 0xFFFF


def parse_freq_table(text: str) -> dict[int, int]:
    out: dict[int, int] = {}
    for m in re.finditer(r"\{\s*(\d+)\s*,\s*(0x[0-9A-Fa-f]+)\s*,", text):
        out[int(m.group(1))] = int(m.group(2), 16)
    return out


def parse_notes(text: str, name: str) -> list[tuple[int, int]]:
    i = text.find(f"const Note {name}[]")
    if i < 0:
        raise SystemExit(f"{name} array not found")
    j = text.find("{", i)
    k = text.find("};", j)
    block = text[j : k + 1]
    return [(int(m.group(1)), int(m.group(2)))
            for m in re.finditer(r"\{\s*(\d+)\s*,\s*(\d+)\s*\}", block)]


def prelude_indices(v1: list[tuple[int, int]], v2: list[tuple[int, int]]) -> tuple[int, int]:
    total_16 = sum(d for _, d in v1)
    target = int(total_16 * PRELUDE_FRAC)
    cum, mel_end = 0, 0
    for idx, (_, d) in enumerate(v1):
        cum += d
        if cum >= target:
            mel_end = idx + 1
            break
    cum, bas_end = 0, 0
    for idx, (_, d) in enumerate(v2):
        cum += d
        if cum >= target:
            bas_end = idx + 1
            break
    return mel_end, bas_end


def main() -> None:
    text = SCRAP.read_text(encoding="utf-8")
    midi_to_freq = parse_freq_table(text)
    v1 = parse_notes(text, "violin1")
    v2 = parse_notes(text, "violin2")

    for midi, _ in v1 + v2:
        if midi not in midi_to_freq:
            midi_to_freq[midi] = midi_to_gb_freq_reg(midi)

    pair_set: dict[tuple[int, int], int] = {}
    def pair_idx(midi: int, d16: int) -> int:
        freq = midi_to_freq[midi]
        dv = max(1, min(255, int(round(d16 * VBL_PER_16TH))))
        key = (freq, dv)
        if key not in pair_set:
            if len(pair_set) >= 255:
                raise SystemExit("more than 254 unique (freq,dur) pairs — doesn't fit 1-byte index + sentinel")
            pair_set[key] = len(pair_set)
        return pair_set[key]

    mel_idx = [pair_idx(m, d) for m, d in v1]
    bas_idx = [pair_idx(m, d) for m, d in v2]
    mel_pre, bas_pre = prelude_indices(v1, v2)
    dict_list = sorted(pair_set.items(), key=lambda x: x[1])

    lines = [
        "/* Auto-generated by tools/emit_bwv1043_c.py — do not edit by hand */",
        '#include <stdint.h>',
        '#include "bwv1043_music.h"',
        "",
        f"const GBNote bwv1043_dict[{len(dict_list)}] = {{",
    ]
    for (freq, dur), _ in dict_list:
        lines.append(f"    {{ {freq}u, {dur}u }},")
    lines.append("};")
    lines.append("")

    def emit_idx(name: str, idxs: list[int]) -> None:
        lines.append(f"const uint8_t {name}[] = {{")
        row: list[str] = []
        for i in idxs:
            row.append(f"{i}u")
            if len(row) == 20:
                lines.append("    " + ", ".join(row) + ",")
                row = []
        row.append(f"{SENTINEL_IDX}u")
        if row:
            lines.append("    " + ", ".join(row) + ",")
        lines.append("};")
        lines.append("")

    emit_idx("bwv1043_melody", mel_idx)
    emit_idx("bwv1043_bass", bas_idx)
    SRC_C.write_text("\n".join(lines) + "\n", encoding="utf-8")

    h_text = SRC_H.read_text(encoding="utf-8")
    replacements = {
        "BWV1043_DICT_LEN": f"{len(dict_list)}u",
        "BWV1043_NUM_MELODY_EVENTS": f"{len(mel_idx) + 1}u",
        "BWV1043_NUM_BASS_EVENTS": f"{len(bas_idx) + 1}u",
        "BWV1043_PRELUDE_END_MELODY": f"{mel_pre}u",
        "BWV1043_PRELUDE_END_BASS": f"{bas_pre}u",
    }
    for macro, val in replacements.items():
        h_text = re.sub(rf"#define {macro} \S+", f"#define {macro} {val}", h_text, count=1)
    SRC_H.write_text(h_text, encoding="utf-8")

    data_bytes = len(dict_list) * 3 + len(mel_idx) + 1 + len(bas_idx) + 1
    print(f"Wrote {SRC_C}: dict={len(dict_list)} entries, mel={len(mel_idx)}, bas={len(bas_idx)}")
    print(f"Total data: {data_bytes} bytes")
    print(f"Prelude ({PRELUDE_FRAC:.0%}): mel_i={mel_pre} bas_i={bas_pre}")


if __name__ == "__main__":
    main()
