//AUTOGENERATED FILE FROM png2asset
// Conversion args: /enemies_miniboss.png -o /enemies_miniboss.c -map -keep_duplicate_tiles -noflip -keep_palette_order

#ifndef METASPRITE_enemies_miniboss_H
#define METASPRITE_enemies_miniboss_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define enemies_miniboss_TILE_ORIGIN 0
#define enemies_miniboss_TILE_W 8
#define enemies_miniboss_TILE_H 8
#define enemies_miniboss_WIDTH 64
#define enemies_miniboss_HEIGHT 8
#define enemies_miniboss_TILE_COUNT 8
#define enemies_miniboss_PALETTE_COUNT 8
#define enemies_miniboss_COLORS_PER_PALETTE 4
#define enemies_miniboss_TOTAL_COLORS 32
#define enemies_miniboss_MAP_ATTRIBUTES 0
extern const unsigned char enemies_miniboss_map[8];
#define enemies_miniboss_map_attributes enemies_miniboss_map

BANKREF_EXTERN(enemies_miniboss)

extern const palette_color_t enemies_miniboss_palettes[32];
extern const uint8_t enemies_miniboss_tiles[128];

#endif
