//AUTOGENERATED FILE FROM png2asset
// Conversion args: /tileset.png -o /tileset.c -map -keep_duplicate_tiles -noflip

#ifndef METASPRITE_tileset_H
#define METASPRITE_tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tileset_TILE_ORIGIN 0
#define tileset_TILE_W 8
#define tileset_TILE_H 8
#define tileset_WIDTH 128
#define tileset_HEIGHT 128
#define tileset_TILE_COUNT 256
#define tileset_PALETTE_COUNT 1
#define tileset_COLORS_PER_PALETTE 4
#define tileset_TOTAL_COLORS 4
#define tileset_MAP_ATTRIBUTES 0
extern const unsigned char tileset_map[256];
#define tileset_map_attributes tileset_map

BANKREF_EXTERN(tileset)

extern const palette_color_t tileset_palettes[4];
extern const uint8_t tileset_tiles[4096];

#endif
