//AUTOGENERATED FILE FROM png2asset
// Conversion args: /tileset.png -c /tileset.c -noflip

#ifndef METASPRITE_tileset_H
#define METASPRITE_tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tileset_TILE_ORIGIN 0
#define tileset_TILE_W 8
#define tileset_TILE_H 16
#define tileset_WIDTH 128
#define tileset_HEIGHT 128
#define tileset_TILE_COUNT 30
#define tileset_PALETTE_COUNT 2
#define tileset_COLORS_PER_PALETTE 4
#define tileset_TOTAL_COLORS 8
#define tileset_PIVOT_X 64
#define tileset_PIVOT_Y 64
#define tileset_PIVOT_W 128
#define tileset_PIVOT_H 128
extern const metasprite_t* const tileset_metasprites[1];

BANKREF_EXTERN(tileset)

extern const palette_color_t tileset_palettes[8];
extern const uint8_t tileset_tiles[480];

#endif
